site_name: PeeringDB
site_url: http://docs.peeringdb.com
repo_url: https://github.com/peeringdb/docs
theme: mkdocs
theme_dir: peeringdb_theme

# dev_addr: 0.0.0.0:7889 # default port was already in use on my box. 

pages:
  - PeeringDB 2.0: index.md
  - Committees: committee.md
  - Governance: gov.md
  - FAQ: faq.md
  - API Specs: api_specs.md

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - nl2br
  - toc

