site_name: PeeringDB
site_url: http://docs.peeringdb.com

pages:
  - PeeringDB 2.0: index.md
  - Committees: committee.md
  - Governance: gov.md
  - FAQ: faq.md
  - API Specs: api_specs.md

markdown_extensions: [abbr,def_list,footnotes,tables,admonition,nl2br,toc]

