site_name: PeeringDB
site_url: http://docs.peeringdb.com
repo_url: https://github.com/peeringdb/docs
theme: mkdocs
theme_dir: peeringdb_theme

pages:
  - PeeringDB: index.md
  - Governance: gov.md
  - Committee:
    - Product: committee/product/index.md
  - FAQ: faq.md
  - API Specs: api_specs.md

extra_css:
  - extra.css

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - markdown_include.include
  - nl2br
  - toc
