site_name: PeeringDB
site_url: http://docs.peeringdb.com
repo_url: https://github.com/peeringdb/docs

pages:
  - PeeringDB: index.md
  - Committees: committee.md
  - Governance: gov.md
  - FAQ: faq.md
  - API Specs: api_specs.md

extra_css:
  - extra.css

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - nl2br
  - toc

