site_name: PeeringDB Docs
site_url: https://docs.peeringdb.com/
theme:
  name: mkdocs
  custom_dir: peeringdb_theme/

nav:
  - About: index.md
  - Governance: gov.md
  - Committees & Task Forces:
    - Admin Committee: committee/admin/index.md
    - Product Committee: committee/product/index.md
    - Data Ownership Task Force: taskforce/dataownership/index.md
  - Technical:
    - API Specs: api_specs.md
    - IX-F JSON: ix-f-json-import-rules.md
    - OAuth: oauth.md
    - Translations: translation.md
  - FAQ: faq.md

extra_css:
  - extra.css

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - markdown_include.include
  - nl2br
  - toc
