site_name: PeeringDB Documentation
site_url: https://docs.peeringdb.com/
repo_url: https://github.com/peeringdb/docs
theme:
  name: mkdocs
  custom_dir: peeringdb_theme/

nav:
  - About PeeringDB: index.md
  - Governance: gov.md
  - Committees:
    - Product Committee: committee/product/index.md
  - Documentation:
    - API Specs: api_specs.md
    - IX-F JSON: ix-f-json-import-rules.md
    - OAuth: oauth.md
    - Translations: translation.md
    - FAQ: faq.md

extra_css:
  - extra.css

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - markdown_include.include
  - nl2br
  - toc
