site_name: PeeringDB
site_url: http://docs.peeringdb.com
repo_url: https://github.com/peeringdb/docs

pages:
  - PeeringDB 2.0: index.md
  - Governance: gov.md
  - FAQ: faq.md
  - API Specs: api_specs.md

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - nl2br
  - toc

